export const regions = [
    {
        id: 1,
        name: 'Tertres',
        region: 'nord',
        hasCastle: true,
        hasHarbor: false,
    },
    {
        id: 2,
        name: 'Blancport',
        region: 'nord',
        hasCastle: false,
        hasHarbor: true,
    },
    {
        id: 3,
        name: 'Neck',
        region: 'nord',
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 4,
        name: 'Don',
        region: 'nord',
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 5,
        name: 'Fort-terreur',
        region: 'nord',
        hasCastle: true,
        hasHarbor: false,
    },
    {
        id: 6,
        name: 'Cap kraken',
        region: 'nord',
        hasCastle: false,
        hasHarbor: true,
    },
    {
        id: 7,
        name: 'Ile-aux-ours',
        region: 'nord',
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 8,
        name: 'Bois-aux-loups',
        region: 'nord',
        hasCastle: false,
        hasHarbor: true,
    },
    {
        id: 9,
        name: 'Winterfell',
        region: 'nord',
        hasCastle: true,
        hasHarbor: false,
    },
    {
        id: 10,
        name: 'La veuve',
        region: 'nord',
        hasCastle: false,
        hasHarbor: true,
    },
    {
        id: 11,
        name: 'Roches',
        region: 'nord',
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 12,
        name: 'Skagos',
        region: 'nord',
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 13,
        name: 'Karhold',
        region: 'nord',
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 14,
        name: "La dent d'or",
        region: "terres de l'ouest",
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 15,
        name: "Montargent",
        region: "terres de l'ouest",
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 16,
        name: "Falaise",
        region: "terres de l'ouest",
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 17,
        name: "Crakehall",
        region: "terres de l'ouest",
        hasCastle: true,
        hasHarbor: false,
    },
    {
        id: 18,
        name: "Castral roc",
        region: "terres de l'ouest",
        hasCastle: true,
        hasHarbor: true,
    },
    {
        id: 19,
        name: "Vivesaigues",
        region: "conflans",
        hasCastle: true,
        hasHarbor: false,
    },
    {
        id: 20,
        name: "Trident",
        region: "conflans",
        hasCastle: false,
        hasHarbor: true,
    },
    {
        id: 21,
        name: "Les jumeaux",
        region: "conflans",
        hasCastle: true,
        hasHarbor: false,
    },
    {
        id: 22,
        name: "Pierremoutier",
        region: "conflans",
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 23,
        name: "Harrenhal",
        region: "conflans",
        hasCastle: true,
        hasHarbor: false,
    },
    {
        id: 24,
        name: "Les eyrié",
        region: "val d'arryn",
        hasCastle: true,
        hasHarbor: false,
    },
    {
        id: 25,
        name: "Doigts",
        region: "val d'arryn",
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 26,
        name: "Montagnes de la lune",
        region: "val d'arryn",
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 27,
        name: "Goeville",
        region: "val d'arryn",
        hasCastle: false,
        hasHarbor: true,
    },
    {
        id: 28,
        name: "La Treille",
        region: "bief",
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 29,
        name: "Route de l'océan",
        region: "bief",
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 30,
        name: "Néra",
        region: "bief",
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 31,
        name: "Trois tours",
        region: "bief",
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 32,
        name: "Mander",
        region: "bief",
        hasCastle: true,
        hasHarbor: false,
    },
    {
        id: 33,
        name: "Hautjardin",
        region: "bief",
        hasCastle: true,
        hasHarbor: false,
    },
    {
        id: 34,
        name: "Villevieille",
        region: "bief",
        hasCastle: true,
        hasHarbor: true,
    },
    {
        id: 35,
        name: "Peyredragon",
        region: "terres de la couronne",
        hasCastle: true,
        hasHarbor: true,
    },
    {
        id: 36,
        name: "Presqu'ile de claquepince",
        region: "terres de la couronne",
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 37,
        name: "Bois du roi",
        region: "terres de la couronne",
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 38,
        name: "Port-Réal",
        region: "terres de la couronne",
        hasCastle: true,
        hasHarbor: true,
    },
    {
        id: 39,
        name: "Ile-de-Torth",
        region: "terres de l'orage",
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 40,
        name: "Bois-la-pluie",
        region: "terres de l'orage",
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 41,
        name: "Marches de Dorne",
        region: "terres de l'orage",
        hasCastle: true,
        hasHarbor: false,
    },
    {
        id: 42,
        name: "Accalmie",
        region: "terres de l'orage",
        hasCastle: true,
        hasHarbor: true,
    },
    {
        id: 43,
        name: "Le Grès",
        region: "dorne",
        hasCastle: true,
        hasHarbor: false,
    },
    {
        id: 44,
        name: "Lancehélion",
        region: "dorne",
        hasCastle: true,
        hasHarbor: true,
    },
    {
        id: 45,
        name: "Montagnes rouges",
        region: "dorne",
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 46,
        name: "Sang-vert",
        region: "dorne",
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 47,
        name: "Pyk",
        region: "Iles de fer",
        hasCastle: false,
        hasHarbor: false,
    },
    {
        id: 48,
        name: "Harloi",
        region: "Iles de fer",
        hasCastle: false,
        hasHarbor: false,
    },

]